import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { BottomNav } from "@/components/BottomNav";
import { isAutoGeneratedUsername } from "@/lib/username";

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect("/login");

  // New users need to pick a username before entering the app
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: profile } = await (supabase as any)
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .single() as { data: { username: string } | null };

  if (!profile || isAutoGeneratedUsername(profile.username)) {
    redirect("/onboarding/username");
  }

  return (
    <div className="flex flex-col h-full">
      <main className="flex-1 overflow-y-auto pb-16">{children}</main>
      <BottomNav />
    </div>
  );
}
