import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { BottomNav } from "@/components/BottomNav";
import { TradeProvider, type TradeProviderData } from "@/components/trade/TradeProvider";
import type { SheetSeason } from "@/components/trade/TradeSheet";
import { isAutoGeneratedUsername } from "@/lib/username";

export default async function AppLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect("/login");

  // New users need to pick a username before entering the app
  const { data: profile } = await supabase
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .single();

  if (!profile || isAutoGeneratedUsername(profile.username)) {
    redirect("/onboarding/username");
  }

  // Data for the global trade overlay. Only the active season is tradeable.
  const { data: season } = await supabase
    .from("seasons")
    .select("id, status, base_price, k_constant")
    .eq("status", "active")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const tradeSeason = season as SheetSeason | null;

  let tradeData: TradeProviderData = {
    season: null,
    contestants: [],
    cashBalance: 0,
    holdings: {},
  };

  if (tradeSeason) {
    const [contestantsResult, portfolioResult, holdingsResult] = await Promise.all([
      supabase
        .from("contestants")
        .select("id, name, photo_url, total_shares_outstanding")
        .eq("season_id", tradeSeason.id)
        .order("name", { ascending: true }),
      supabase
        .from("portfolios")
        .select("cash_balance")
        .eq("user_id", user.id)
        .eq("season_id", tradeSeason.id)
        .maybeSingle(),
      supabase
        .from("holdings")
        .select("contestant_id, shares_held")
        .eq("user_id", user.id),
    ]);

    const holdings: Record<string, number> = {};
    for (const h of holdingsResult.data ?? []) {
      holdings[h.contestant_id] = h.shares_held;
    }

    tradeData = {
      season: tradeSeason,
      contestants: contestantsResult.data ?? [],
      cashBalance: portfolioResult.data?.cash_balance ?? 0,
      holdings,
    };
  }

  return (
    <TradeProvider data={tradeData}>
      <div className="flex flex-col h-full">
        {/* Clearance = BottomNav height (h-16) + its safe-area padding. */}
        <main className="flex-1 overflow-y-auto pb-[calc(4rem+env(safe-area-inset-bottom))]">
          {children}
        </main>
        <BottomNav />
      </div>
    </TradeProvider>
  );
}
