import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { isAutoGeneratedUsername } from "@/lib/username";
import { UsernameForm } from "./UsernameForm";

export default async function PickUsernamePage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) redirect("/login");

  // Already has a real username — skip onboarding
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: profile } = await (supabase as any)
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .single() as { data: { username: string } | null };

  if (profile && !isAutoGeneratedUsername(profile.username)) {
    redirect("/market");
  }

  return (
    <div className="min-h-full flex flex-col items-center justify-center p-6">
      <div className="w-full max-w-sm space-y-8">
        <div className="space-y-2">
          <h1 className="text-2xl font-bold tracking-tight">Pick a username</h1>
          <p className="text-sm text-neutral-400">
            This is how you&apos;ll appear on the leaderboard and to other players.
          </p>
        </div>
        <UsernameForm />
      </div>
    </div>
  );
}
