import leoProfanity from "leo-profanity";

leoProfanity.loadDictionary();

const MIN = 3;
const MAX = 20;
// Starts with letter, then letters/numbers/underscores
const FORMAT_RE = /^[a-zA-Z][a-zA-Z0-9_]*$/;
// No consecutive underscores
const CONSECUTIVE_RE = /__/;

export type UsernameRule = {
  label: string;
  pass: (value: string) => boolean;
};

/** Ordered list of format rules shown in the requirements list. */
export const USERNAME_RULES: UsernameRule[] = [
  {
    label: `${MIN}–${MAX} characters`,
    pass: (v) => v.length >= MIN && v.length <= MAX,
  },
  {
    label: "Starts with a letter",
    pass: (v) => /^[a-zA-Z]/.test(v),
  },
  {
    label: "Letters, numbers, and underscores only",
    pass: (v) => FORMAT_RE.test(v),
  },
  {
    label: "No consecutive underscores",
    pass: (v) => !CONSECUTIVE_RE.test(v),
  },
];

export type UsernameFormatResult =
  | { ok: true }
  | { ok: false; error: string };

/** Validate format only — no DB check. Safe to run on client or server. */
export function validateUsernameFormat(value: string): UsernameFormatResult {
  if (value.length < MIN) return { ok: false, error: `Must be at least ${MIN} characters` };
  if (value.length > MAX) return { ok: false, error: `Must be ${MAX} characters or fewer` };
  if (!/^[a-zA-Z]/.test(value)) return { ok: false, error: "Must start with a letter" };
  if (!FORMAT_RE.test(value)) return { ok: false, error: "Letters, numbers, and underscores only" };
  if (CONSECUTIVE_RE.test(value)) return { ok: false, error: "No consecutive underscores" };
  if (leoProfanity.check(value)) return { ok: false, error: "Username not allowed" };
  return { ok: true };
}

/** True if the username looks auto-generated (i.e. not yet chosen by the user). */
export function isAutoGeneratedUsername(username: string): boolean {
  return /^user_[0-9a-f]{8}$/.test(username);
}
